import Link from 'next/link';
import { Check, ScanLine, ShieldCheck, Sparkles, WifiOff } from 'lucide-react';
import { renderQR, DEFAULT_STYLE } from '@moduqr/renderer';

export default function HomePage() {
  const hero = renderQR('https://example.com', { ...DEFAULT_STYLE, moduleShape: 'rounded', finderOuterShape: 'rounded', finderInnerShape: 'circle', gradient: { type: 'linear', angle: 45, stops: [{ offset: 0, color: '#111827' }, { offset: 1, color: '#5b4cf0' }] } }, 640);
  const softwareJson = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'ModuQR', applicationCategory: 'DesignApplication', operatingSystem: 'Web', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, description: 'Privacy-first open-source QR generator, designer and scanner.' };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareJson).replace(/</g, '\\u003c') }}/><div className="shell"><section className="hero"><div><span className="eyebrow"><Sparkles size={14}/> Design without breaking scanability</span><h1>QR design with a reliability layer.</h1><p className="hero-copy">ModuQR is an open-source, privacy-first QR studio. Create polished static codes locally, see scan risks before exporting, and redesign scanned codes without routing your payload through a server.</p><div className="hero-actions"><Link className="button accent" href="/generator">Open QR Studio</Link><Link className="button" href="/scanner">Scan an image</Link></div><div className="hero-proof"><span><Check size={14}/> Local static generation</span><span><Check size={14}/> SVG-first renderer</span><span><Check size={14}/> No account required</span></div></div><div className="hero-card"><div className="hero-qr" dangerouslySetInnerHTML={{ __html: hero.svg }}/><div className="hero-card-footer"><div><strong>Live design preview</strong><span>Generated from the same export renderer</span></div><div className="score-pill">Scan checks enabled</div></div></div></section><section className="feature-grid" aria-label="Core capabilities"><Feature icon={<ShieldCheck size={22}/>} title="Scan Safety" text="Contrast, quiet-zone, density, logo, module-size, gradient, and real decode signals feed one explainable report."/><Feature icon={<WifiOff size={22}/>} title="Private by default" text="Static payloads, logos, scanner images, and local projects stay in the browser. Static QR codes do not expire."/><Feature icon={<ScanLine size={22}/>} title="Scan → Redesign" text="Decode an existing QR image, inspect its content safely, then open the payload directly in the same design engine."/></section></div></>;
}
function Feature({ icon, title, text }: Readonly<{ icon: React.ReactNode; title: string; text: string }>) { return <article className="feature-card">{icon}<h2>{title}</h2><p>{text}</p></article>; }
