import type { SeoPageContent } from '@/components/seo-page';

export const seoContent = {
  generator: { eyebrow: 'Private static QR', title: 'Free QR code generator with design controls', intro: 'Generate custom static QR codes without an account, tracking redirect, or server dependency.', bullets: ['Local payload encoding', 'SVG-first custom rendering', 'Scan-safety checks before export'], faq: [{ q: 'Do static QR codes expire?', a: 'No. A static QR contains its payload directly and does not depend on a ModuQR redirect service.' }, { q: 'Is my QR content uploaded?', a: 'The static studio is designed to encode payloads locally in the browser.' }], available: true },
  url: { eyebrow: 'URL QR', title: 'Create a QR code for a website URL', intro: 'Turn a web address into a styled QR while keeping the destination directly inside the static code.', bullets: ['URL validation', 'Logo-safe rendering', 'PNG, SVG, JPEG, WebP, and PDF export'], faq: [{ q: 'Can I change the destination later?', a: 'Not for a static QR. Changing a destination after printing requires an optional dynamic redirect mode, planned for the server platform.' }], available: true },
  wifi: { eyebrow: 'WiFi QR', title: 'Create a private WiFi QR code', intro: 'Encode SSID, security mode, hidden-network status, and password locally.', bullets: ['WPA/WPA2/WPA3-compatible payload format', 'Escaped SSIDs and passwords', 'Sensitive content is not put into a share URL'], faq: [{ q: 'Does ModuQR store my WiFi password?', a: 'The static studio processes WiFi input locally. Saved projects live in IndexedDB on your device.' }], available: true },
  vcard: { eyebrow: 'Contact QR', title: 'Create a vCard QR code', intro: 'Package contact fields into a vCard 3.0 payload that can be scanned into contact apps.', bullets: ['Name and organization', 'Phone and email', 'Website and title'], faq: [{ q: 'Which vCard version is generated?', a: 'The current static generator emits vCard 3.0 for broad compatibility.' }], available: true },
  whatsapp: { eyebrow: 'Messaging QR', title: 'Create a WhatsApp QR code', intro: 'Build a wa.me link with a phone number and optional prefilled message.', bullets: ['Normalized phone number', 'Optional encoded message', 'Static destination with no ModuQR redirect'], faq: [{ q: 'Does this send a message automatically?', a: 'No. Scanning opens the WhatsApp destination; the user still controls the action.' }], available: true },
  email: { eyebrow: 'Email QR', title: 'Create an email QR code', intro: 'Generate a mailto QR with recipient, subject, and message body.', bullets: ['Validated recipient', 'Encoded subject and body', 'Local generation'], faq: [{ q: 'Will scanning send the email?', a: 'No. It opens a compatible email client with fields prepared.' }], available: true },
  text: { eyebrow: 'Text QR', title: 'Create a plain text QR code', intro: 'Encode notes, identifiers, instructions, or any plain text directly.', bullets: ['No redirect', 'No account', 'Works offline after the app is cached'], faq: [{ q: 'How much text should I put in a QR?', a: 'QR standards support large payloads, but dense codes are harder to scan. ModuQR flags density and module-size risks.' }], available: true },
  image: { eyebrow: 'Image QR', title: 'Create a QR code for an image', intro: 'For normal images, use a stable image URL. Very large binary image data does not belong directly inside a practical QR code.', bullets: ['Honest capacity guidance', 'Use a stable image URL for normal files', 'Embedded-data analysis is planned for the professional studio'], faq: [{ q: 'Can a full photo be embedded directly?', a: 'Usually not in a practical, reliably scannable QR. A URL is the recommended approach for ordinary images.' }], available: true },
  pdf: { eyebrow: 'PDF QR', title: 'Create a QR code for a PDF link', intro: 'Point a static QR at a stable PDF URL rather than pretending a normal PDF can fit directly into a QR.', bullets: ['URL-based PDF sharing', 'No fake file hosting in static mode', 'PDF export refers to exporting the QR artwork itself'], faq: [{ q: 'Does ModuQR host my PDF?', a: 'No. Hosted files are a future server-mode capability and are not part of the current static application.' }], available: true },
  social: { eyebrow: 'Social QR', title: 'Create a QR code for a social profile', intro: 'Use a profile URL for Instagram, YouTube, GitHub, LinkedIn, Telegram, or other social destinations.', bullets: ['Works with normal profile URLs', 'Social-oriented design presets', 'No tracking redirect in static mode'], faq: [{ q: 'Can one QR contain multiple social links?', a: 'A static QR can contain a single payload. A multi-link landing page needs an existing URL or a later hosted server feature.' }], available: true },
  logo: { eyebrow: 'Logo QR', title: 'Create a QR code with a logo', intro: 'Upload a local PNG, JPEG, WebP, or sanitized SVG and keep finder patterns protected.', bullets: ['Center cutout', 'Automatic High error correction when a logo is added', 'Decode verification before export'], faq: [{ q: 'Can a logo make a QR unreadable?', a: 'Yes. ModuQR limits logo size, protects finder regions, and verifies rendered output before download.' }], available: true },
  designer: { eyebrow: 'QR design studio', title: 'Design a QR without sacrificing scanability', intro: 'Control module shapes, finder styles, gradients, quiet zones, logos, frames, and presets from one SVG renderer.', bullets: ['One renderer for preview and export', '60 currently shipped data-defined presets', 'Real decode checks feed the safety score'], faq: [{ q: 'Is this just a qr-code-styling wrapper?', a: 'No. Encoding produces a matrix; ModuQR owns its SVG rendering and design layer.' }], available: true },
  scanner: { eyebrow: 'Local scanner', title: 'Scan and redesign a QR code from an image', intro: 'Decode an uploaded, dropped, or pasted image locally, inspect the payload, then send it to the designer.', bullets: ['No automatic URL opening', 'Content-type detection', 'Payload transfer to the designer uses same-tab session storage'], faq: [{ q: 'Can I scan with my camera?', a: 'Yes, when the browser grants camera access in a supported secure context. Local image upload remains available as a fallback.' }], available: true, ctaHref: '/scanner', ctaLabel: 'Open QR Scanner' },
  batch: { eyebrow: 'Phase 2 · local batch', title: 'Batch QR code generator', intro: 'Generate up to 500 verified QR codes locally from CSV, TSV, or JSON, then export SVG/PNG ZIPs or PDF sheets.', bullets: ['Up to 500 rows per run', 'Web Worker preparation with local-only dataset handling', 'Preflight decode verification for every exported QR'], faq: [{ q: 'Is batch generation available now?', a: 'Yes. Batch preparation and exports run locally in your browser; the dataset is not uploaded to ModuQR.' }], available: true },
  dynamic: { eyebrow: 'Phase 3', title: 'Self-hosted dynamic QR codes', intro: 'Dynamic redirects, editable destinations, analytics, API keys, and PostgreSQL server mode are planned for Phase 3.', bullets: ['Static generator remains serverless', 'Dynamic mode uses real short redirect URLs', 'Self-hosting is a core requirement'], faq: [{ q: 'Can I edit a static QR destination?', a: 'No. Editable destinations require a dynamic redirect service, which is intentionally not faked in the current static application.' }], available: false },
} as const satisfies Record<string, SeoPageContent>;
